/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/casio_classwiz_calculator.glb -o components/models/Calculator.tsx -t -r public -K 
Author: Niilo Poutanen (https://sketchfab.com/niilo.poutanen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/casio-classwiz-calculator-22ac8280c1434e5f8b41e2fdec45abd6
Title: Casio classwiz calculator
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.LineSegments
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
  }
  materials: {
    Func: THREE.MeshStandardMaterial
    Lasi: THREE.MeshStandardMaterial
    Musta_muovi: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Nytt: THREE.MeshStandardMaterial
    harmaa: THREE.LineBasicMaterial | THREE.MeshStandardMaterial
    Napit: THREE.MeshStandardMaterial
    Runko: THREE.MeshPhysicalMaterial
  }
}

export function Calculator(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/casio_classwiz_calculator.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group>
            <mesh geometry={nodes.Object_2.geometry} material={materials.Func} />
            <mesh geometry={nodes.Object_3.geometry} material={materials.Lasi} />
            <mesh geometry={nodes.Object_4.geometry} material={materials.Musta_muovi} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Nytt} />
            <lineSegments geometry={nodes.Object_7.geometry} material={materials.harmaa} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.harmaa} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.Napit} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Runko} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/casio_classwiz_calculator.glb')
